name: lecteurmultimedia
description: lecteurmultimedia flutter app for neopolis.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.8.1
  json_serializable: ^3.5.1
  equatable: ^1.2.5
  http: ^0.12.0
  flutter_bloc: ^6.1.0
  meta: ^1.1.8
  assets_audio_player: ^2.0.13

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/


  fonts:
    - family: SFProDisplay
      fonts:
        - asset: fonts/FontsFree-Net-SFProDisplay-Light.ttf
        - asset: fonts/FontsFree-Net-SFProDisplay-Regular.ttf








